### ISSUE TITLE
Plugin can no longer communicate with Harvest

### ISSUE THREAD

**Issue by sdishman** [Strategery-Inc/jira-harvest-time-tracker#73] opened 2016-10-03 15:25 UTC
Starting this morning (I think?) our plugin no longer works.  We are using v2.5.2 as this is the highest version that is compatible with our JIRA version.  Here is a screenshot of the error that all of our users are seeing:

![strategery-jira-harvest-plugin-error](https://cloud.githubusercontent.com/assets/314529/19042910/efaee1a8-895b-11e6-8c70-ff8d1d6e8d1c.png)

(Note that I have blanked out the user/pass fields, but those did have correct values in them prior to generating the screenshot)

**Comment by gsomoza** [comment] 2016-10-03 15:31
This is a widespread issue that we believe affects most of our users. It started to happen today, an hour or two ago. We still don't know what's causing it, but since nothing major changed our our end I have reached out to Harvest to see if they made any changes to their API.

Meanwhile we'll check to see if there's anything we can do work around it or fix it. We'll post an update here when we have more information.

Sorry for the inconvenience.

**Comment by sdishman** [comment] 2016-10-03 15:33
Thanks for the super-fast update.  Sorry if I created a duplicate issue, I did a brief glance and didn't notice anything related to it that was opened today...

**Comment by gsomoza** [comment] 2016-10-03 15:35
I believe this is the first report on Github, thanks for doing that!

**Comment by openlucho** [comment] 2016-10-03 15:36
We're having the same issue.  Our Jira sever is reporting a bad SSL certificate at harvest.systems.  Is there anyway to work around this?  I opened a ticket with Harvest as well.

Front-End:
Request URL:https://ourjirainstall.com/plugins/servlet/harvest/time
Request Method:POST
Status Code:401 Unauthorized

Back-end:
javax.net.ssl.SSLException: hostname in certificate didn't match:
<ourharvestinstall.harvestapp.com> != <*.harvest.systems> OR <*.harvest.systems> OR <harvest.systems>

**Comment by openlucho** [comment] 2016-10-03 15:37
harvest.systems doesn't have a valid certificate installed.

Common name: getharvest.com
SANs: coopapp.com, www.coopapp.com, www.iridesco.com, iridesco.com, www.forecastapp.com, forecastapp.com, api.forecastapp.com, www.getharvest.com, id.getharvest.com, getharvest.com

**Comment by gsomoza** [comment] 2016-10-03 15:41
Thanks for the info `openlucho`, I'm already in contact with Harvest about this. I do suspect this could be on their end because everything was working just a few hours ago, and we didn't change anything on our end.

Quick question for both: are you using the latest version of the plugin? If you are, it might be worth checking if downgrading to the previous one solves the issue, then we can discard that possibility. 

Unfortunately I can't do that test right now because our company also happens to be performing maintenance on our own JIRA instance, so we can't even try doing that at the moment...

**Comment by gsomoza** [comment] 2016-10-03 15:46
I just issued manually several requests to the Harvest API and they do work. So it's unlikely that's the issue... We'll continue to debug.

**Comment by openlucho** [comment] 2016-10-03 15:49
We're on Version:3.0.4.  If a downgrade will require a Jira restart, I wouldn't be able to test until after 7pm central.

**Comment by sdishman** [comment] 2016-10-03 16:04
We are using v2.5.2.

**Comment by gsomoza** [comment] 2016-10-03 16:06
Ah, thanks for that @sdishman - that discards the possibility of recent changes on our end causing this.. 

That means we'll have to wait for Harvest's response regarding any changes on their end..

Once again, apologies to everyone for the inconvenience..

**Comment by gsomoza** [comment] 2016-10-03 16:14
I can confirm the following error (also reported by @openlucho) is what's causing the issue:

```
==> logs/catalina.out <==
javax.net.ssl.SSLException: hostname in certificate didn't match: <strategery.harvestapp.com> != <*.harvest.systems> OR <*.harvest.systems> OR <harvest.systems>
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:220)
```

Looks like this is a problem on the SSL certificate from Harvest. I've sent them this information to see if they can resolve this ASAP. Stay tuned.

**Comment by openlucho** [comment] 2016-10-03 18:31
This just started working for us again.

**Comment by gsomoza** [comment] 2016-10-03 18:45
Yes, for us too. Harvest just confirmed they fixed the issue on their end! Closing this ticket.

**Closed by gsomoza** 2016-10-03 18:45 UTC
