### ISSUE TITLE
Time logged in Harvest but not in JIRA tempo

### ISSUE THREAD

**Issue by simpoul** [Strategery-Inc/jira-harvest-time-tracker#78] opened 2017-06-14 14:28 UTC
There was an update made by JIRA on the "Timesheet" component this morning at 2am and since then the plugin is not working properly. We did a "re-index" of JIRA but it did not worked. Time get logged in Harvest but not in JIRA. 
<img width="542" alt="capture d ecran 2017-06-14 a 10 26 17" src="https://user-images.githubusercontent.com/6109021/27137433-f1779ac2-50eb-11e7-8d36-70e14a9c1318.png">
The screenshot says that I did logged 2 hours, but there is nothing in the Tempo timesheet.

**Comment by gsomoza** [comment] 2017-06-19 17:35
Thanks for reporting this, we'll take a look as soon as possible. Just to confirm: are you using the "cloud" version of JIRA?

**Comment by simpoul** [comment] 2017-06-19 18:57
Yes! And after more investigation, we found that the time gets correctly logged, but like few hours after. There's is a big delay between the time you log time and you can see it in the task.

**Comment by gsomoza** [comment] 2017-06-20 08:33
That's indeed really weird. All our plugin does is issue an AJAX call to the JIRA API, through their own library, and that happens *immediately* after the timer is stopped. So if the time does eventually get logged then it would seem that the call succeeds, only that JIRA doesn't update the ticket until after several hours.. Almost as if the update was put on a queue or something for later processing (which I think is entirely possible, e.g. if they're using an API Gateway or something like that).

In any case I'm afraid that means the issue is likely not on our end (especially since we send that request immediately)... Could you try getting in touch with JIRA support about this?

**Comment by simpoul** [comment] 2017-06-20 13:43
I think you're right, there might be a kind of queue somewhere that gets processed later... I'll try to get in touch with JIRA. Thank you Gabriel!

**Comment by gsomoza** [comment] 2017-06-20 20:52
Sure, no problem - make sure to let me know if it gets resolved so we can close this ticket. And if there's anything else I can do please don't hesitate to ask.

**Comment by gsomoza** [comment] 2018-06-14 09:05
Closed due to inactivity

**Closed by gsomoza** 2018-06-14 09:05 UTC
Labels: ready
