### ISSUE TITLE
Weird Display Issues in Latest Cloud Version

### ISSUE THREAD

**Issue by ericaherschorn** [Strategery-Inc/jira-harvest-time-tracker#86] opened 2018-05-18 14:57 UTC
Hi there, 
as of today I am not able to log time using the time tracker.  Can you please advise how to login so we're able to track our time?

Steps:
- Click button - track time
- This pop up appears
<img width="812" alt="screen shot 2018-05-18 at 9 51 37 am" src="https://user-images.githubusercontent.com/13858169/40241928-ca29d99e-5a81-11e8-99c1-0210642a4f8b.png">
- There's no where to log in (I am already logged into harvest inside of my browser)
- My colleagues are experiencing the same issue

I also see a console error which likely is related

<img width="1205" alt="screen shot 2018-05-18 at 9 54 36 am" src="https://user-images.githubusercontent.com/13858169/40241962-e19eeb46-5a81-11e8-9fda-db9bf43a8717.png">

**Comment by gsomoza** [comment] 2018-05-18 15:05
Hi @ericaherschorn - this looks like an issue with the latest version of the plugin that was released today. Did you already upgrade to that latest version?

We weren't able to reproduce your issue in two of our JIRA Cloud environments. Could you please try uninstalling the plugin and re-installing it? 

If that doesn't work I would recommend downgrading to the previous version until we're able to resolve this issue.

**Comment by ericaherschorn** [comment] 2018-05-18 15:26
Hi @gsomoza 

Thanks for the quick reply. 

We didn't manually upgrade to the latest version, I think it might do it automatically. This is the version we are on:
<img width="1044" alt="screen shot 2018-05-18 at 10 24 41 am" src="https://user-images.githubusercontent.com/13858169/40243390-bebfd8ac-5a85-11e8-97b7-adfd7da6b696.png">

i clicked unsubscribe, and now it is not letting me uninstall bc our current billing cycle continues.

**Comment by ericaherschorn** [comment] 2018-05-18 15:28
I also not able to re-subscribe now...

**Comment by ericaherschorn** [comment] 2018-05-18 15:30
Could it be due to the old version of JIRA vs. the new version? I've not yet updated (I don't particularly like it).

**Comment by neris** [comment] 2018-05-18 15:34
Hi @ericaherschorn,  
The error that you can see in the console is not triggered by our add-on.  
Looks like you have some strange padding inside the modal window created by JIRA, it prevents you from seeing the 'Log in' button located below the 'Harvest authentication expired' message. Maybe it's somehow related to the old version of UI that you're using (unfortunately, we can't quickly test if it's true).  
Can you please provide a little more information about the system(s) this issue appears on? OS, browser version.

**Comment by neris** [comment] 2018-05-18 15:35
Also, can you try to disable other JIRA add-ons if you have any?

**Comment by gsomoza** [comment] 2018-05-18 15:51
@ericaherschorn basically it does seem like it could be a JIRA compatibility issue. We didn't realize the update would happen "automatically" for customers like you because it's a completely new version of the add-on and the "major" number is new as well (2018... instead of 2014...). Apologies for that automatic upgrade.

The information that @neris requested would be very useful, so if you can help us with that then it might give us something to work with. But since we don't have a Jira Cloud instance that's running the old version I'm afraid it would be hard for us to troubleshoot this anyways.

So the only short-term solution I can think of is to figure out a way to get you back to the older version of the add-on. Could you email us at support@strategery.io? I could try sharing a link to a private listing of the previous version – hopefully that will fix the issue.

Regarding the subscription: I don't think that will affect your ability to use the add-on during the rest of the billing period. Additionally, we're planning on releasing this latest version as completely new plugin anyways, so once this billing cycle expires you'll have to switch to the other plugin anyways (or at least that's the current plan). There's no data to be migrated so the switch should be mostly seamless.

**Comment by neris** [comment] 2018-05-18 15:57
@ericaherschorn,
We've found the problem and indeed it's related to the old JIRA UI. We will fix it as soon as possible.

**Comment by ericaherschorn** [comment] 2018-05-18 15:59
Hi all,

Thanks for your attention & focus on this. In the mean time, would you be able to provide the link so we can go back to the old version?

**Comment by gsomoza** [comment] 2018-05-18 16:01
@ericaherschorn could you email us at support@strategery.io? We'll send you the link through that channel because the only way to downgrade seems to be to switch to a private listing version of the add-on – we're not even sure if that will work, but it should be worth trying.

FYI if @neris fix works then that should be ready within an hour or two max, if not sooner.

**Comment by ericaherschorn** [comment] 2018-05-18 16:02
oh we can totally wait a couple hours- I thought it would be a couple days. We have the other harvest add on implemented right now as our back up.

Pls keep us posted - thanks!
Erica

**Comment by neris** [comment] 2018-05-18 16:50
@ericaherschorn, the problem should be fixed now. Can you please try to refresh the JIRA issue page and see if it works now?

**Comment by ericaherschorn** [comment] 2018-05-18 16:51
It works! 🎉 

Thank you so much for your super speedy fix. It's much appreciated.

Looking fwd to using the new version,
Erica

**Comment by gsomoza** [comment] 2018-05-18 16:53
@ericaherschorn so glad to hear that! Thanks for your feedback and I hope you enjoy the new version.

I'll leave this ticket open because other customers also reported layout issues similar to yours. They should also be resolved by this same fix, but I'll close this later once that's confirmed across more customers.

**Comment by gsomoza** [comment] 2018-05-21 11:03
Confirmed closed by other customers as well.

**Closed by gsomoza** 2018-05-21 11:03 UTC
