### ISSUE TITLE
Ability to use the plugin when using Google SSO for Harvest

### ISSUE THREAD

**Issue by albgus** [Strategery-Inc/jira-harvest-time-tracker#89] opened 2018-08-07 09:22 UTC
**Is your feature request related to a problem? Please describe.**
We have some accounts that are setup using Google account Single-Sign On to authenticate with Harvest. At the moment it isn't possible to setup these accounts with the Harvest Jira plugins because it asks for a username and password that doesn't exist when using SSO authentication.

**Describe the solution you'd like**
A proper OAuth connection between Harvest and the Jira instance should probably solve this issue, as it would not be specifically dependent on a username and password.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gsomoza** [comment] 2018-08-29 08:01
@albgus you'll have to access the accounts via Harvest to set a password for them. Once you did that, you should be able to login using the email address and that password.

Closing because this is not a bug in the extension, but feel free to ask follow up questions if necessary.

**Closed as completed by gsomoza** 2018-08-29 08:01 UTC
