### ISSUE TITLE
Wrong URL to Harvest

### ISSUE THREAD

**Issue by cprieto741** [Strategery-Inc/jira-harvest-time-tracker#42] opened 2015-04-30 18:57 UTC
The links provided in the Harvest Time Tracking popup are incorrect. They show an additional "https//" in the link for "Overview" & "My Timesheet" so the link looks like:

https://https//corporation.harvestapp.com

**Comment by meirlipskier** [comment] 2015-04-30 19:00
Why am I getting emails regarding tickets for this plugin that I am not
involved with??
This is the 3rd time already.

Please update your notification scheme to only notify relevant parties
involved!


Meir Lipskier

On Thu, Apr 30, 2015 at 11:57 AM, cprieto741 <notifications@github.com>
wrote:

> The links provided in the Harvest Time Tracking popup are incorrect. They
> show an additional "https//" in the link for "Overview" & "My Timesheet" so
> the link looks like:
>
> https://https//corporation.harvestapp.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strategery-Inc/jira-harvest-time-tracker/issues/42>.
>



-- 

*Meir Lipskier*

*Director of Tech Operations*

*PRODEGE LLC*

*P. (310)735-0552 x 201*

*M. (310)704-4051*

**Comment by gabrielsomoza** [comment] 2015-05-04 17:18
@meirlipskier we don't have control over a "notification scheme" here at Github - but you do: 

1. Go to the repository's main page (https://github.com/Strategery-Inc/jira-harvest-time-tracker) 
2. Right next to the title there are 3 buttons: Unwatch, Star and Fork. Click on the Unwatch button to see a menu.
3. Select your desired option.

**Comment by gabrielsomoza** [comment] 2015-05-04 17:19
@cprieto741 at the prompt when logging in did you enter "https://" at the beginning of the first field? That could be the cause of the issue.

Either way, its definitely a bug.

**Comment by gabrielsomoza** [comment] 2015-05-06 13:34
@NicolaXB try to log out (from the popup dialog) - that should allow you to enter different credentials and a different URL.

We'll make sure this gets fixed in the next release.

**Comment by gabrielsomoza** [comment] 2015-06-04 12:59
Closing this because it will be addressed with #44. Please subscribe to that ticket for updates.

**Closed by gabrielsomoza** 2015-06-04 12:59 UTC
Labels: bug
