### ISSUE TITLE
Time Logging Notes do not log in Jira

### ISSUE THREAD

**Issue by estan1** [Strategery-Inc/jira-harvest-time-tracker#68] opened 2016-04-01 15:36 UTC
Jira Cloud

Steps to Reproduce
1. Go to an issue and click the Track Time plugin button
2. Notes (optional) field. Do not touch the default text that shows up. Hit Enter 2 times and then add some extra billable comments & notes.
3. Fill the other details and click Start Tracking
4. Go to the Jira issue Work Log tab and see the worklog in Jira that was just created

Expected Result
The worklog entry in Jira should contain the same bailable comments/notes as filled in Harvest

Actual Result
The Jira Work Description field for the time entry is empty. 

This is very confusing and is a major pain point for our stats/reports in Jira for each issue and in general.
Can you please fix asap?

**Comment by estan1** [comment] 2016-04-01 15:59
Seems this is similar to this one:
https://github.com/Strategery-Inc/jira-harvest-time-tracker/issues/52

**Comment by gsomoza** [comment] 2016-04-01 17:55
Its indeed that one, so I'll close this one. It will still be referenced by the other one so we can come back to this for the steps to reproduce.

We'll try to get both of the tickets you reported today closed by ends of May at the latest.

**Comment by gsomoza** [comment] 2020-04-15 09:56
Closing due to inactivity / old issue

**Closed by gsomoza** 2020-04-15 09:56 UTC
